#!/bin/bash
set -e

echo "Executing PSQL script..."

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" <<-EOSQL
  CREATE USER $POSTGRES_DB_USERNAME WITH PASSWORD '$POSTGRES_DB_PASSWORD';
  ALTER ROLE $POSTGRES_DB_USERNAME SET client_encoding TO 'utf8';
  ALTER ROLE $POSTGRES_DB_USERNAME SET default_transaction_isolation TO 'read committed';
  ALTER ROLE $POSTGRES_DB_USERNAME SET timezone TO 'Europe/Moscow';
  CREATE DATABASE $POSTGRES_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB_NAME TO $POSTGRES_DB_USERNAME;
EOSQL
