version: "3.6"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5430:5432"
    volumes:
      - "dbdata:/var/lib/postgresql"
      - "./scripts/initdb/:/docker-entrypoint-initdb.d"
#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - .:/app
#    ports:
#      - 3000:3000
#    depends_on:
#      - db

volumes:
  dbdata:
