FROM python:3.9-alpine

RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev libffi-dev

# Set work directory:
WORKDIR /app

# Expose ports:
EXPOSE 3000

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV FLASK_ENV=development
ENV FLASK_DEBUG=1

# Copy and install requirements
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["/bin/sh"]
